#####################################
# 1. Upgrade all Packages on Server #
#####################################

  - name: Upgrade all Packages Latest
    apt: update_cache=yes upgrade=full cache_valid_time=86400 #One day
